import numpy as np
import matplotlib.pyplot as plt 

MS_sigma=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/MS_dispersion.txt', unpack=True)
MS_eta, MS_xi=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/MS_smoothed_goodcenters.txt', usecols=(0,1,), unpack=True)
RG_sigma=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/RG_dispersion.txt', unpack=True)
RG_eta, RG_xi=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/RG_smoothed_goodcenters.txt', usecols=(0,1,), unpack=True)
AGo_sigma=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/AGo_dispersion.txt', unpack=True)
AGo_eta, AGo_xi=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/AGo_smoothed_goodcenters.txt', usecols=(0,1,), unpack=True)
AGy_sigma=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/AGy_dispersion.txt', unpack=True)
AGy_eta, AGy_xi=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/AGy_smoothed_goodcenters.txt', usecols=(0,1,), unpack=True)

#plotting 
plt.scatter(AGy_xi, AGy_eta, s=1, c=AGy_sigma, cmap='copper',vmin=10,vmax=150)
plt.xlim(-.5,1)
plt.gca().invert_xaxis()
plt.ylim(-1,1.2)
plt.xlabel('xi (deg)')
plt.ylabel('eta (deg)')
clb=plt.colorbar()
clb.set_label('v dispersion (km/s)')
plt.savefig('/Users/amandaquirk/Desktop/AGy_dispersion.png')
plt.close()

plt.scatter(AGo_xi, AGo_eta, s=1, c=AGo_sigma, cmap='copper',vmin=10,vmax=150)
plt.xlim(-.5,1)
plt.gca().invert_xaxis()
plt.ylim(-1,1.2)
plt.xlabel('xi (deg)')
plt.ylabel('eta (deg)')
clb=plt.colorbar()
clb.set_label('v dispersion (km/s)')
plt.savefig('/Users/amandaquirk/Desktop/AGo_dispersion.png')
plt.close()

plt.scatter(RG_xi, RG_eta, s=1, c=RG_sigma, cmap='copper',vmin=10,vmax=150)
plt.xlim(-.5,1)
plt.gca().invert_xaxis()
plt.ylim(-1,1.2)
plt.xlabel('xi (deg)')
plt.ylabel('eta (deg)')
clb=plt.colorbar()
clb.set_label('v dispersion (km/s)')
plt.savefig('/Users/amandaquirk/Desktop/RG_dispersion.png')
plt.close()
