import numpy as np 
import matplotlib.pyplot as plt 

MS_ad=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/MS_ad.txt')
MS_tang=np.loadtxt('/Users/amandaquirk/Desktop/MS_components.txt', usecols=(0,), unpack=True)
AGy_ad=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/AGy_ad.txt')
AGy_tang=np.loadtxt('/Users/amandaquirk/Desktop/AGy_components.txt', usecols=(0,), unpack=True)
AGo_ad=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/AGo_ad.txt')
AGo_tang=np.loadtxt('/Users/amandaquirk/Desktop/AGo_components.txt', usecols=(0,), unpack=True)
RG_ad=np.loadtxt('/Users/amandaquirk/Documents/AsymmetricDrift/Data/RG_ad.txt')
RG_tang=np.loadtxt('/Users/amandaquirk/Desktop/RG_components.txt', usecols=(0,), unpack=True)

#do numpy polyfit to get my line of best fit
MS_z=np.polyfit([a*a for a,b in zip(MS_tang, MS_ad) if b>=-20], [a for a in MS_ad if a>-20], 1)
AGy_z=np.polyfit([a*a for a,b in zip(AGy_tang, AGy_ad) if b>=-20], [a for a in AGy_ad if a>-20], 1)
AGo_z=np.polyfit([a*a for a,b in zip(AGo_tang, AGo_ad) if b>=-20], [a for a in AGo_ad if a>-20], 1)
RG_z=np.polyfit([a*a for a,b in zip(RG_tang, RG_ad) if b>=-20], [a for a in RG_ad if a>-20], 1)

plt.figure(figsize=(10, 6))
plt.scatter([a*a for a in MS_tang], MS_ad, s=5, c='k')
plt.plot([0,22500], [MS_z[1],22500*MS_z[0]], c='b')
plt.xlabel(r'$\sigma_{\phi}^{2}$')
plt.ylabel('Asymmetric Drift')
plt.ylim(-20,140)
plt.xlim(0, 20000)
plt.savefig('/Users/amandaquirk/Desktop/MS_ad_sig_tan.png')
plt.close()

plt.figure(figsize=(10, 6))
plt.scatter([a*a for a in AGy_tang], AGy_ad, s=5, c='k')
plt.plot([0,22500], [AGy_z[1],22500*AGy_z[0]], c='m')
plt.xlabel(r'$\sigma_{\phi}^{2}$')
plt.ylabel('Asymmetric Drift')
plt.ylim(-20,140)
plt.xlim(0, 20000)
plt.savefig('/Users/amandaquirk/Desktop/AGy_ad_sig_tan.png')
plt.close()

plt.figure(figsize=(10, 6))
plt.scatter([a*a for a in AGo_tang], AGo_ad, s=5, c='k')
plt.plot([0,22500], [AGo_z[1],22500*AGo_z[0]], c='m')
plt.xlabel(r'$\sigma_{\phi}^{2}$')
plt.ylabel('Asymmetric Drift')
plt.ylim(-20,140)
plt.xlim(0, 20000)
plt.savefig('/Users/amandaquirk/Desktop/AGo_ad_sig_tan.png')
plt.close()

plt.figure(figsize=(10, 6))
plt.scatter([a*a for a in RG_tang], RG_ad, s=5, c='k')
plt.plot([0,22500], [RG_z[1],22500*RG_z[0]], c='r')
plt.xlabel(r'$\sigma_{\phi}^{2}$')
plt.ylabel('Asymmetric Drift')
plt.ylim(-20,140)
plt.xlim(0, 20000)
plt.savefig('/Users/amandaquirk/Desktop/RG_ad_sig_tan.png')
plt.close()